/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "on-tertiary": "#ffffff",
        "surface": "#fbf8ff",
        "tertiary-fixed": "#e4e2de",
        "outline-variant": "#c4c7c7",
        "on-secondary": "#ffffff",
        "on-primary-container": "#858484",
        "on-primary-fixed": "#1b1b1b",
        "on-primary-fixed-variant": "#474746",
        "secondary-container": "#ffdb94",
        "inverse-on-surface": "#f1effa",
        "surface-container-low": "#f4f2fd",
        "surface-container": "#eeedf7",
        "on-tertiary-fixed-variant": "#474744",
        "surface-bright": "#fbf8ff",
        "primary-fixed-dim": "#c8c6c5",
        "on-secondary-fixed-variant": "#5a4309",
        "inverse-primary": "#c8c6c5",
        "tertiary-fixed-dim": "#c8c6c3",
        "secondary": "#745b20",
        "on-tertiary-container": "#858481",
        "on-surface": "#1a1b22",
        "primary-container": "#1c1c1c",
        "on-secondary-fixed": "#261a00",
        "on-secondary-container": "#795f24",
        "surface-container-lowest": "#ffffff",
        "surface-variant": "#e3e1ec",
        "on-surface-variant": "#444748",
        "on-primary": "#ffffff",
        "surface-tint": "#5f5e5e",
        "surface-container-high": "#e8e7f1",
        "on-error-container": "#93000a",
        "inverse-surface": "#2f3038",
        "tertiary-container": "#1b1c1a",
        "secondary-fixed": "#ffdf9f",
        "primary-fixed": "#e5e2e1",
        "error-container": "#ffdad6",
        "secondary-fixed-dim": "#e4c27d",
        "on-tertiary-fixed": "#1b1c1a",
        "surface-dim": "#dad9e3",
        "surface-container-highest": "#e3e1ec",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "primary": "#010101",
        "on-background": "#1a1b22",
        "background": "#fbf8ff",
        "tertiary": "#010100",
        "outline": "#747878"
      },
      "borderRadius": {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      "spacing": {
        "card-padding": "24px",
        "max-width-content": "1440px",
        "unit": "4px",
        "margin-page": "40px",
        "gutter": "24px"
      },
      "fontFamily": {
        "headline-md-mobile": ["DM Serif Display", "serif"],
        "data-metric": ["IBM Plex Sans", "sans-serif"],
        "body-main": ["Source Sans 3", "sans-serif"],
        "label-caps": ["Source Sans 3", "sans-serif"],
        "display-lg": ["DM Serif Display", "serif"],
        "headline-md": ["DM Serif Display", "serif"],
        "data-tabular": ["IBM Plex Sans", "sans-serif"],
        "title-sm": ["Source Sans 3", "sans-serif"]
      },
      "fontSize": {
        "headline-md-mobile": ["24px", {"lineHeight": "32px", "fontWeight": "400"}],
        "data-metric": ["24px", {"lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "500"}],
        "body-main": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "label-caps": ["12px", {"lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "700"}],
        "display-lg": ["48px", {"lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "400"}],
        "headline-md": ["32px", {"lineHeight": "40px", "fontWeight": "400"}],
        "data-tabular": ["14px", {"lineHeight": "20px", "fontWeight": "450"}],
        "title-sm": ["18px", {"lineHeight": "24px", "letterSpacing": "0.01em", "fontWeight": "600"}]
      }
    },
  },
  plugins: [],
}
